language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: scheul93@gmail.com
  api_key:
    secure: f6mc5H5eN9TtpwlOc4b2D0zkCIxYecoD21gnbVsat8B+1LgEWCXldfqg8plR0kYBzh1nuE4EavOHnecLR5b8qcLcBXReeuTUMaNt17W8XTgiLgcMtBD/ulaP6LSGLw2JccqZUmR557Ic+sTjkkQJJbi5N4R6ptZtyXRGpyE0cUm8a7QNaqmfN2+fj99HKPVGsKvHFxipHa5mPCykViCKkbgxXr1AhzTxsG0XHth3QCJ6/dbWRhjUaytfNvb8AKL5ooCKCEvdwnRy+tyeg6BPmNmQFEjQbrL/vBWbUhXlLjWdTyl07K3plOVUqOa6Xuabm8X4ujT6xEFIqaH0jA81zX3qWyLskbN+2d+g6PdUZidWE8i6MOcgIjyotKrsgMOW4E38tdCUbKt8/ZbOYdAS1Tho9UQyu2q1x8MEXDw0g/LI8vwV/njh75DIfAZmcLBSuReUnr2E1VV7Xhnpev4FtxmL4+3jFscmayzMdSGXLP9ROrsiBccM/OHKhb6b5nVv4rBMWuFOaiuHxaUtatG4q+RDkm+V2z/CSNOvCyjl4dBWIep/ng18XeqCUjn0KwAuC2CI0pC/NOHcE39pmd2O7pX08m3j4Hsp+WOufw3zavaXVOncvvvButCRPKLx1+0+NJkoo6gojXnMMlUwA6USSsW13RfhGXHNUFVqIDDpTyc=
  on:
    tags: true
    branch: master
    repo: DEGJS/formValidation-email
